/*
 * pytoken.h - UmerOS Python Token Types
 */

#ifndef UMEROS_PYTOKEN_H
#define UMEROS_PYTOKEN_H

#include "object.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    TOKEN_EOF = 0,

    /* Literals */
    TOKEN_INTEGER,
    TOKEN_FLOAT,
    TOKEN_STRING,
    TOKEN_NAME,
    TOKEN_TRUE,
    TOKEN_FALSE,
    TOKEN_NONE,

    /* Keywords */
    TOKEN_IF,
    TOKEN_ELIF,
    TOKEN_ELSE,
    TOKEN_WHILE,
    TOKEN_FOR,
    TOKEN_IN,
    TOKEN_BREAK,
    TOKEN_CONTINUE,
    TOKEN_RETURN,
    TOKEN_DEF,
    TOKEN_CLASS,
    TOKEN_IMPORT,
    TOKEN_FROM,
    TOKEN_AND,
    TOKEN_OR,
    TOKEN_NOT,
    TOKEN_IS,
    TOKEN_LAMBDA,
    TOKEN_TRY,
    TOKEN_EXCEPT,
    TOKEN_FINALLY,
    TOKEN_RAISE,
    TOKEN_WITH,
    TOKEN_AS,
    TOKEN_YIELD,
    TOKEN_GLOBAL,
    TOKEN_NONLOCAL,
    TOKEN_ASSERT,
    TOKEN_DEL,
    TOKEN_PASS,
    TOKEN_ASYNC,
    TOKEN_AWAIT,

    /* Operators */
    TOKEN_PLUS,
    TOKEN_MINUS,
    TOKEN_STAR,
    TOKEN_DOUBLE_STAR,
    TOKEN_SLASH,
    TOKEN_DOUBLE_SLASH,
    TOKEN_PERCENT,
    TOKEN_EQ,
    TOKEN_EQEQ,
    TOKEN_NOTEQ,
    TOKEN_LT,
    TOKEN_GT,
    TOKEN_LE,
    TOKEN_GE,
    TOKEN_AND_AND,
    TOKEN_OR_OR,
    TOKEN_NOT_NOT,
    TOKEN_TILDE,
    TOKEN_COLON_EQUAL,

    /* Delimiters */
    TOKEN_LPAREN,
    TOKEN_RPAREN,
    TOKEN_LBRACKET,
    TOKEN_RBRACKET,
    TOKEN_LBRACE,
    TOKEN_RBRACE,
    TOKEN_COMMA,
    TOKEN_SEMICOLON,
    TOKEN_COLON,
    TOKEN_DOT,
    TOKEN_ARROW,
    TOKEN_ELLIPSIS,

    /* Assignment */
    TOKEN_PLUS_EQUAL,
    TOKEN_MINUS_EQUAL,
    TOKEN_STAR_EQUAL,
    TOKEN_SLASH_EQUAL,
    TOKEN_PERCENT_EQUAL,
    TOKEN_AMPERSAND_EQUAL,
    TOKEN_PIPE_EQUAL,
    TOKEN_CARET_EQUAL,
    TOKEN_DOUBLE_STAR_EQUAL,
    TOKEN_DOUBLE_SLASH_EQUAL,
    TOKEN_RSHIFT_EQUAL,
    TOKEN_LSHIFT_EQUAL,

    /* Bitwise */
    TOKEN_AMPERSAND,
    TOKEN_PIPE,
    TOKEN_CARET,
    TOKEN_RSHIFT,
    TOKEN_LSHIFT,

    /* Special */
    TOKEN_NEWLINE,
    TOKEN_INDENT,
    TOKEN_DEDENT,
    TOKEN_COMMENT,
    TOKEN_WHITESPACE,
    TOKEN_ERROR,

    TOKEN_AT
} TokenType;

/* Compatibility aliases for compiler.c */
#define TOKEN_KEYWORD_FALSE  TOKEN_FALSE
#define TOKEN_KEYWORD_TRUE   TOKEN_TRUE
#define TOKEN_KEYWORD_NONE   TOKEN_NONE
#define TOKEN_KEYWORD_AND      TOKEN_AND
#define TOKEN_KEYWORD_AS       TOKEN_AS
#define TOKEN_KEYWORD_ASSERT   TOKEN_ASSERT
#define TOKEN_KEYWORD_ASYNC    TOKEN_ASYNC
#define TOKEN_KEYWORD_AWAIT    TOKEN_AWAIT
#define TOKEN_KEYWORD_BREAK    TOKEN_BREAK
#define TOKEN_KEYWORD_CLASS    TOKEN_CLASS
#define TOKEN_KEYWORD_CONTINUE TOKEN_CONTINUE
#define TOKEN_KEYWORD_DEF      TOKEN_DEF
#define TOKEN_KEYWORD_DEL      TOKEN_DEL
#define TOKEN_KEYWORD_ELIF     TOKEN_ELIF
#define TOKEN_KEYWORD_ELSE     TOKEN_ELSE
#define TOKEN_KEYWORD_EXCEPT   TOKEN_EXCEPT
#define TOKEN_KEYWORD_FINALLY  TOKEN_FINALLY
#define TOKEN_KEYWORD_FOR      TOKEN_FOR
#define TOKEN_KEYWORD_FROM     TOKEN_FROM
#define TOKEN_KEYWORD_GLOBAL   TOKEN_GLOBAL
#define TOKEN_KEYWORD_IF       TOKEN_IF
#define TOKEN_KEYWORD_IMPORT   TOKEN_IMPORT
#define TOKEN_KEYWORD_IN       TOKEN_IN
#define TOKEN_KEYWORD_IS       TOKEN_IS
#define TOKEN_KEYWORD_LAMBDA   TOKEN_LAMBDA
#define TOKEN_KEYWORD_NONLOCAL TOKEN_NONLOCAL
#define TOKEN_KEYWORD_NOT      TOKEN_NOT
#define TOKEN_KEYWORD_OR       TOKEN_OR
#define TOKEN_KEYWORD_PASS     TOKEN_PASS
#define TOKEN_KEYWORD_RAISE    TOKEN_RAISE
#define TOKEN_KEYWORD_RETURN   TOKEN_RETURN
#define TOKEN_KEYWORD_TRY      TOKEN_TRY
#define TOKEN_KEYWORD_WHILE    TOKEN_WHILE
#define TOKEN_KEYWORD_WITH     TOKEN_WITH
#define TOKEN_KEYWORD_YIELD    TOKEN_YIELD
#define TOKEN_LEFTSHIFT      TOKEN_LSHIFT
#define TOKEN_RIGHTSHIFT     TOKEN_RSHIFT
#define TOKEN_LESSEQUAL      TOKEN_LE
#define TOKEN_GREATEREQUAL   TOKEN_GE
#define TOKEN_LESS           TOKEN_LT
#define TOKEN_GREATER        TOKEN_GT
#define TOKEN_NOTEQUAL       TOKEN_NOTEQ
#define TOKEN_PLUSEQUAL      TOKEN_PLUS_EQUAL
#define TOKEN_MINEQUAL       TOKEN_MINUS_EQUAL
#define TOKEN_DOUBLESTAR     TOKEN_DOUBLE_STAR
#define TOKEN_STAREQUAL      TOKEN_STAR_EQUAL
#define TOKEN_DOUBLESLASH    TOKEN_DOUBLE_SLASH
#define TOKEN_SLASHEQUAL     TOKEN_SLASH_EQUAL
#define TOKEN_PERCENTEQUAL   TOKEN_PERCENT_EQUAL
#define TOKEN_NL             TOKEN_NEWLINE
#define TOKEN_NUMBER         TOKEN_INTEGER
#define TOKEN_ENDMARKER      TOKEN_EOF
#define TOKEN_EQUAL          TOKEN_EQ

/* Token structure */
typedef struct {
    TokenType type;
    char *value;
    Py_ssize_t length;
    int line;
    int column;
} Token;

#ifdef __cplusplus
}
#endif

#endif /* UMEROS_PYTOKEN_H */
