"""
Umer OS Initrd Scenarios
========================
The four "usage scenarios" from the TLDP ``/initrd`` reference, plus a
fifth one (``per_machine``) that maps directly to the second TLDP
motivation ("different hardware configurations in a single
administrative domain").

Each scenario is a self-contained :class:`InitrdScenario` that owns:

* A description (shown to the user via the GUI / CLI).
* A list of "things this scenario must do" (file creation, module
  loading, hook installation, AI hints).
* An entry-point coroutine that the :mod:`initrd.linuxrc` runner
  calls once the initrd has been mounted as root.

Scenarios are pure data: they never touch the VFS or the phase
machine directly.  That keeps them easy to unit-test in isolation.

Author:  Umer OS Project
Licence: Apache 2.0
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Awaitable, Callable, Dict, List, Optional

from initrd.cpio import CpioEntry, newc_dir, newc_file, newc_symlink
from initrd.module_resolver import ModuleResolver, ModuleSpec, ModuleReason

log = logging.getLogger("UmerOS.Initrd.Scenarios")


# ---------------------------------------------------------------------------
# Built-in scenario IDs
# ---------------------------------------------------------------------------

class ScenarioId(str, Enum):
    """The five scenarios that ship with Umer OS."""

    NORMAL     = "normal"       # Plain boot: load modules, mount, pivot.
    INSTALL    = "install"      # First-boot: detect media, set up /, write image.
    RECOVERY   = "recovery"     # Damaged real root: drop to a rescue shell.
    LIVE       = "live"         # Live CD: keep initrd as final root.
    RESCUE     = "rescue"       # No real root - stay in the initrd shell.
    PER_MACHINE = "per_machine" # Per-machine config layered on top of NORMAL.


# ---------------------------------------------------------------------------
# Scenario dataclass
# ---------------------------------------------------------------------------

@dataclass
class InitrdScenario:
    """A pre-canned ``/linuxrc`` strategy."""

    id: ScenarioId
    title: str
    description: str
    extra_modules: List[str] = field(default_factory=list)
    extra_files: Dict[str, bytes] = field(default_factory=dict)
    extra_directories: List[str] = field(default_factory=list)
    extra_symlinks: Dict[str, str] = field(default_factory=dict)
    extra_hooks: Dict[str, List[str]] = field(default_factory=dict)
    keep_as_root: bool = False
    interactive: bool = False
    notes: List[str] = field(default_factory=list)

    def resolve_modules(self, resolver: ModuleResolver) -> List[ModuleSpec]:
        """Add this scenario's modules to ``resolver`` and return them."""
        specs: List[ModuleSpec] = []
        for name in self.extra_modules:
            spec = resolver._lookup(name)  # noqa: SLF001 - intentional
            if spec is None:
                log.warning("scenario %s: unknown module %s", self.id.value, name)
                continue
            tagged = ModuleSpec(
                name=spec.name,
                reason=ModuleReason.SCENARIO,
                parameters=dict(spec.parameters),
                dependencies=list(spec.dependencies),
                source=f"scenario:{self.id.value}",
            )
            resolver.selected[tagged.name] = tagged
            specs.append(tagged)
        return specs

    def build_entries(self, base_entries: List[CpioEntry]) -> List[CpioEntry]:
        """Return ``base_entries`` plus this scenario's extra files."""
        out: List[CpioEntry] = list(base_entries)
        ino = 1000 + len(out)
        # Directories
        for d in self.extra_directories:
            out.append(newc_dir(d, ino=ino))
            ino += 1
        # Files
        for path, data in self.extra_files.items():
            out.append(newc_file(path, data=data, ino=ino))
            ino += 1
        # Symlinks
        for src, target in self.extra_symlinks.items():
            out.append(newc_symlink(src, target, ino=ino))
            ino += 1
        return out


# ---------------------------------------------------------------------------
# Catalogue
# ---------------------------------------------------------------------------

SCENARIO_CATALOGUE: Dict[ScenarioId, InitrdScenario] = {
    ScenarioId.NORMAL: InitrdScenario(
        id=ScenarioId.NORMAL,
        title="Normal boot",
        description=(
            "Default two-phase boot. /linuxrc loads the modules "
            "required to mount the real root, then pivots and execs "
            "/sbin/init."
        ),
        extra_modules=["ext4", "ahci"],
        extra_files={
            "/etc/hostname":   b"umer-os\n",
            "/etc/fstab":      b"# generated by UmerOS initrd\n",
        },
        extra_directories=["/etc", "/var/log", "/run", "/tmp"],
        keep_as_root=False,
        interactive=False,
    ),

    ScenarioId.INSTALL: InitrdScenario(
        id=ScenarioId.INSTALL,
        title="First-boot installation",
        description=(
            "Used at install time: /linuxrc asks the user (or auto-"
            "probes) for the media type, loads the matching modules, "
            "creates a minimal root FS, pivots into it and runs the "
            "installer.  After success, the boot loader is configured "
            "to load a smaller initrd containing only the modules "
            "actually used."
        ),
        extra_modules=["ext4", "btrfs", "xfs", "vfat", "ahci", "nvme", "virtio_blk"],
        extra_directories=[
            "/install", "/install/media", "/install/target",
        ],
        extra_files={
            "/install/README":   b"Umer OS installation environment\n",
            "/etc/issue":        b"Umer OS installer \\n \\l\n",
        },
        extra_symlinks={
            "/bin/sh": "/bin/busybox",
        },
        extra_hooks={
            "pre_mount_real_root": ["install::probe_media"],
            "post_pivot_root":     ["install::run_installer"],
        },
        keep_as_root=False,
        interactive=True,
        notes=[
            "Matches TLDP phase 1 - 'system boots from floppy or "
            "other media with a minimal kernel'.",
        ],
    ),

    ScenarioId.RECOVERY: InitrdScenario(
        id=ScenarioId.RECOVERY,
        title="Recovery / damaged root",
        description=(
            "When the real root is unreadable / corrupted. /linuxrc "
            "drops to an interactive shell so the operator can run "
            "fsck, mount the root by hand, or restore from backup. "
            "Matches the third TLDP motivation - 'more convenient "
            "recovery disks'."
        ),
        extra_modules=["ext4", "btrfs", "xfs", "vfat", "ahci", "nvme", "dm_mod"],
        extra_directories=["/recovery", "/recovery/logs"],
        extra_files={
            "/recovery/HOWTO": (
                b"Welcome to the Umer OS recovery shell.\n"
                b"Try: mount -t ext4 /dev/sda2 /newroot\n"
            ),
        },
        extra_symlinks={"/bin/sh": "/bin/busybox"},
        extra_hooks={"pre_pivot_root": ["recovery::drop_to_shell"]},
        keep_as_root=True,
        interactive=True,
    ),

    ScenarioId.LIVE: InitrdScenario(
        id=ScenarioId.LIVE,
        title="Live system (CD / USB)",
        description=(
            "The initrd stays mounted as the final root for the "
            "whole session.  No pivot_root, no second-stage image. "
            "Matches the fourth TLDP motivation - 'CD-ROM "
            "distributors may use it for better installation from CD'."
        ),
        extra_modules=["overlay", "squashfs", "loop"],
        extra_directories=["/live", "/live/filesystem.squashfs"],
        extra_files={
            "/live/README":      b"Umer OS Live image\n",
            "/etc/issue":        b"Umer OS Live \\n \\l\n",
        },
        extra_symlinks={"/bin/sh": "/bin/busybox"},
        keep_as_root=True,
        interactive=False,
    ),

    ScenarioId.RESCUE: InitrdScenario(
        id=ScenarioId.RESCUE,
        title="Rescue shell",
        description=(
            "Even less than recovery - we never even try to mount a "
            "real root.  Useful when the disk is missing entirely."
        ),
        extra_modules=[],
        extra_directories=["/rescue"],
        extra_files={
            "/rescue/HELP": b"No root device was found.  Power off safely.\n",
        },
        extra_symlinks={"/bin/sh": "/bin/busybox"},
        keep_as_root=True,
        interactive=True,
    ),

    ScenarioId.PER_MACHINE: InitrdScenario(
        id=ScenarioId.PER_MACHINE,
        title="Per-machine override",
        description=(
            "Layered on top of NORMAL.  Reads /etc/umeros/"
            "initrd.local.conf to add the modules and files this "
            "particular machine needs.  Matches the second TLDP "
            "motivation - 'a single kernel + per-machine initrd'."
        ),
        extra_modules=[],
        extra_files={
            "/etc/umeros/README": (
                b"Drop a file called initrd.local.conf here; it "
                b"will be sourced at boot to add per-machine "
                b"modules and mounts.\n"
            ),
        },
        extra_directories=["/etc/umeros"],
        keep_as_root=False,
        interactive=False,
        notes=[
            "This is what makes a small generic kernel + small "
            "generic initrd work across an entire fleet.",
        ],
    ),
}


def get_scenario(sid: ScenarioId) -> InitrdScenario:
    """Return the built-in scenario for ``sid`` (raises if unknown)."""
    if sid not in SCENARIO_CATALOGUE:
        raise KeyError(f"unknown scenario: {sid}")
    return SCENARIO_CATALOGUE[sid]


def list_scenarios() -> List[ScenarioId]:
    return list(SCENARIO_CATALOGUE.keys())


# ---------------------------------------------------------------------------
# Scenario runner
# ---------------------------------------------------------------------------

class ScenarioRunner:
    """Executes a scenario against the live :mod:`initrd.linuxrc` state."""

    def __init__(self, scenario: InitrdScenario) -> None:
        self.scenario = scenario

    def apply_modules(self, resolver: ModuleResolver) -> List[ModuleSpec]:
        return self.scenario.resolve_modules(resolver)

    def apply_files(self, entries: List[CpioEntry]) -> List[CpioEntry]:
        return self.scenario.build_entries(entries)

    def should_keep_as_root(self) -> bool:
        return self.scenario.keep_as_root

    def summary(self) -> Dict[str, Any]:
        return {
            "id":          self.scenario.id.value,
            "title":       self.scenario.title,
            "interactive": self.scenario.interactive,
            "modules":     list(self.scenario.extra_modules),
            "files":       list(self.scenario.extra_files),
            "directories": list(self.scenario.extra_directories),
            "symlinks":    dict(self.scenario.extra_symlinks),
            "hooks":       {k: list(v) for k, v in self.scenario.extra_hooks.items()},
            "notes":       list(self.scenario.notes),
        }


# ---------------------------------------------------------------------------
# Self-test
# ---------------------------------------------------------------------------

def _selftest() -> bool:
    s = get_scenario(ScenarioId.NORMAL)
    if "ext4" not in s.extra_modules:
        return False
    r = ModuleResolver()
    s.resolve_modules(r)
    if "ext4" not in r.selected:
        return False
    entries = s.build_entries([])
    # Cpio entries keep the leading "/" from the path.
    has_hostname = any(e.name == "/etc/hostname" for e in entries)
    return has_hostname


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    print("scenarios selftest:", "OK" if _selftest() else "FAIL")
