#!/usr/bin/env python3
"""
UmerOS - /etc/cron* and /var/spool/cron manager
Manages cron jobs: /etc/crontab, /etc/cron.d/*, /etc/cron.{hourly,daily,weekly,monthly}/*,
/var/spool/cron/crontabs/*, /etc/anacrontab, /etc/cron.allow, /etc/cron.deny.
Also manages 'at' and 'batch' jobs via /var/spool/at and /var/spool/batch.
"""
import os, re, json, hashlib, shutil
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Optional, Any, Union

CRON_DIRS = {
    "system": "/etc/cron.d",
    "hourly": "/etc/cron.hourly",
    "daily": "/etc/cron.daily",
    "weekly": "/etc/cron.weekly",
    "monthly": "/etc/cron.monthly",
}
CRONTAB_PATHS = {
    "system": "/etc/crontab",
    "var_spool": "/var/spool/cron/crontabs",
}
ANACRONTAB = "/etc/anacrontab"
AT_DIR = "/var/spool/at"
BATCH_DIR = "/var/spool/batch"
CRON_ALLOW = "/etc/cron.allow"
CRON_DENY = "/etc/cron.deny"
CRON_LOG = "/var/log/cron.log"
CRON_MAIL_DIR = "/var/spool/mail"

CRON_TIME_RE = re.compile(
    r"^(?P<minute>[0-9*/,\-]+)\s+"
    r"(?P<hour>[0-9*/,\-]+)\s+"
    r"(?P<day>[0-9*/,\-]+)\s+"
    r"(?P<month>[0-9*/,\-]+)\s+"
    r"(?P<weekday>[0-9*/,\-]+)\s+"
    r"(?P<command>.+)$"
)
CRON_D_TIME_RE = re.compile(
    r"^(?P<minute>[0-9*/,\-]+)\s+"
    r"(?P<hour>[0-9*/,\-]+)\s+"
    r"(?P<day>[0-9*/,\-]+)\s+"
    r"(?P<month>[0-9*/,\-]+)\s+"
    r"(?P<weekday>[0-9*/,\-]+)\s+"
    r"(?P<user>\S+)\s+"
    r"(?P<command>.+)$"
)
ANACRON_RE = re.compile(
    r"^(?P<period>\d+|monthly|weekly|daily|hourly)\s+"
    r"(?P<delay>\d+)?\s*"
    r"(?P<job_id>\S+)\s+"
    r"(?P<command>.+)$"
)


class CronScheduleManager:
    """Manages cron jobs, cron directories, anacron, at, and batch jobs."""

    def __init__(self):
        for d in CRON_DIRS.values():
            Path(d).mkdir(parents=True, exist_ok=True)
        for p in [CRONTAB_PATHS["system"], CRONTAB_PATHS["var_spool"]]:
            Path(p).parent.mkdir(parents=True, exist_ok=True)
        Path(AT_DIR).mkdir(parents=True, exist_ok=True)
        Path(BATCH_DIR).mkdir(parents=True, exist_ok=True)
        Path(CRON_LOG).parent.mkdir(parents=True, exist_ok=True)

    # ── crontab parsing and management ──────────────────────────────
    def parse_system_crontab(self) -> List[Dict[str, Any]]:
        """Parse /etc/crontab and return all valid cron entries."""
        return self._parse_crontab_file(Path(CRONTAB_PATHS["system"]), is_system=True)

    def parse_user_crontab(self, username: str) -> List[Dict[str, Any]]:
        """Parse a user's crontab from /var/spool/cron/crontabs/<username>."""
        user_file = Path(CRONTAB_PATHS["var_spool"]) / username
        return self._parse_crontab_file(user_file, is_system=False)

    def list_user_crontabs(self) -> List[str]:
        """List all user crontab files that exist."""
        user_crons = []
        spool_dir = Path(CRONTAB_PATHS["var_spool"])
        if spool_dir.exists():
            for f in spool_dir.iterdir():
                if f.is_file():
                    user_crons.append(f.name)
        return user_crons

    def set_user_crontab(self, username: str, entries: List[str]) -> Dict[str, Any]:
        """Write a crontab for a user."""
        user_file = Path(CRONTAB_PATHS["var_spool"]) / username
        valid_entries = []
        errors = []
        for entry in entries:
            entry = entry.strip()
            if not entry or entry.startswith("#"):
                valid_entries.append(entry)
                continue
            parsed = self._parse_cron_entry(entry)
            if parsed:
                valid_entries.append(entry)
            else:
                errors.append(f"Invalid cron entry: {entry}")
        if errors:
            return {"action": "failed", "user": username, "errors": errors}
        user_file.parent.mkdir(parents=True, exist_ok=True)
        content = f"# Crontab for {username} - generated by UmerOS\n"
        content += f"# Do NOT edit by hand — use 'crontab -e' or UmerOS\n"
        content += f"MAILTO={username}\n\n"
        content += "\n".join(valid_entries) + "\n"
        user_file.write_text(content)
        return {"action": "written", "user": username, "entries": len(valid_entries)}

    def delete_user_crontab(self, username: str) -> Dict[str, Any]:
        """Delete a user's crontab."""
        user_file = Path(CRONTAB_PATHS["var_spool"]) / username
        if user_file.exists():
            user_file.unlink()
            return {"action": "deleted", "user": username}
        return {"action": "not_found", "user": username}

    # ── cron.d directory management ──────────────────────────────────
    def list_cron_d(self) -> List[Dict[str, Any]]:
        """List all files in /etc/cron.d with their parsed entries."""
        return self._list_cron_dir(Path(CRON_DIRS["system"]))

    def add_cron_d(self, filename: str, entries: List[str], owner: str = "root",
                   perms: int = 0o644) -> Dict[str, Any]:
        """Add a new file to /etc/cron.d."""
        cron_d_file = Path(CRON_DIRS["system"]) / filename
        valid_entries = []
        errors = []
        for entry in entries:
            entry = entry.strip()
            if not entry or entry.startswith("#"):
                valid_entries.append(entry)
                continue
            parsed = self._parse_cron_d_entry(entry)
            if parsed:
                valid_entries.append(entry)
            else:
                errors.append(f"Invalid cron.d entry (must include user field): {entry}")
        if errors:
            return {"action": "failed", "file": filename, "errors": errors}
        content = f"# {filename} — managed by UmerOS\n"
        content += "\n".join(valid_entries) + "\n"
        cron_d_file.write_text(content)
        os.chmod(cron_d_file, perms)
        return {"action": "added", "file": filename, "entries": len(valid_entries)}

    def remove_cron_d(self, filename: str) -> Dict[str, Any]:
        """Remove a file from /etc/cron.d."""
        cron_d_file = Path(CRON_DIRS["system"]) / filename
        if cron_d_file.exists():
            cron_d_file.unlink()
            return {"action": "removed", "file": filename}
        return {"action": "not_found", "file": filename}

    # ── cron directories (hourly/daily/weekly/monthly) ───────────────
    def list_cron_dir(self, period: str) -> List[str]:
        """List scripts in a cron directory."""
        d = CRON_DIRS.get(period)
        if not d:
            return []
        return [f.name for f in Path(d).iterdir() if f.is_file()]

    def add_cron_script(self, period: str, name: str, script_content: str,
                        perms: int = 0o755) -> Dict[str, Any]:
        """Add a script to a cron directory."""
        d = CRON_DIRS.get(period)
        if not d:
            return {"error": f"Invalid period: {period}", "action": "failed"}
        script_path = Path(d) / name
        script_path.write_text(script_content)
        os.chmod(script_path, perms)
        return {"action": "added", "period": period, "script": name, "path": str(script_path)}

    def remove_cron_script(self, period: str, name: str) -> Dict[str, Any]:
        """Remove a script from a cron directory."""
        d = CRON_DIRS.get(period)
        if not d:
            return {"error": f"Invalid period: {period}", "action": "failed"}
        script_path = Path(d) / name
        if script_path.exists():
            script_path.unlink()
            return {"action": "removed", "period": period, "script": name}
        return {"action": "not_found", "period": period, "script": name}

    # ── anacrontab ───────────────────────────────────────────────────
    def parse_anacrontab(self) -> List[Dict[str, Any]]:
        """Parse /etc/anacrontab."""
        return self._parse_anacrontab_file(Path(ANACRONTAB))

    def set_anacrontab(self, entries: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Write /etc/anacrontab."""
        content = "# /etc/anacrontab — managed by UmerOS\n"
        content += "# period  delay  job-id  command\n"
        for entry in entries:
            period = entry.get("period", "daily")
            delay = entry.get("delay", 5)
            job_id = entry.get("job_id", "")
            command = entry.get("command", "")
            if not job_id or not command:
                continue
            content += f"{period}  {delay}  {job_id}  {command}\n"
        Path(ANACRONTAB).write_text(content)
        return {"action": "written", "entries": len(entries)}

    # ── at and batch jobs ────────────────────────────────────────────
    def list_at_jobs(self) -> List[Dict[str, Any]]:
        """List scheduled at jobs."""
        return self._list_spool_jobs(AT_DIR)

    def list_batch_jobs(self) -> List[Dict[str, Any]]:
        """List scheduled batch jobs."""
        return self._list_spool_jobs(BATCH_DIR)

    def add_at_job(self, name: str, schedule: str, command: str,
                   user: str = "root") -> Dict[str, Any]:
        """Add an at job."""
        job_data = {
            "name": name,
            "schedule": schedule,
            "command": command,
            "user": user,
            "created": datetime.now().isoformat(),
            "state": "pending",
        }
        job_path = Path(AT_DIR) / name
        job_path.write_text(json.dumps(job_data, indent=2))
        return {"action": "added", "name": name, "schedule": schedule}

    def remove_at_job(self, name: str) -> Dict[str, Any]:
        """Remove an at job."""
        job_path = Path(AT_DIR) / name
        if job_path.exists():
            job_path.unlink()
            return {"action": "removed", "name": name}
        return {"action": "not_found", "name": name}

    def add_batch_job(self, name: str, command: str, user: str = "root") -> Dict[str, Any]:
        """Add a batch job."""
        job_data = {
            "name": name,
            "command": command,
            "user": user,
            "created": datetime.now().isoformat(),
            "state": "pending",
        }
        job_path = Path(BATCH_DIR) / name
        job_path.write_text(json.dumps(job_data, indent=2))
        return {"action": "added", "name": name}

    def remove_batch_job(self, name: str) -> Dict[str, Any]:
        """Remove a batch job."""
        job_path = Path(BATCH_DIR) / name
        if job_path.exists():
            job_path.unlink()
            return {"action": "removed", "name": name}
        return {"action": "not_found", "name": name}

    # ── access control ───────────────────────────────────────────────
    def set_cron_allow(self, users: List[str]) -> Dict[str, Any]:
        """Set /etc/cron.allow — only these users can use cron."""
        content = "\n".join(users) + "\n"
        Path(CRON_ALLOW).write_text(content)
        return {"action": "written", "users": users}

    def set_cron_deny(self, users: List[str]) -> Dict[str, Any]:
        """Set /etc/cron.deny — these users cannot use cron."""
        content = "\n".join(users) + "\n"
        Path(CRON_DENY).write_text(content)
        return {"action": "written", "users": users}

    def get_cron_access(self) -> Dict[str, Any]:
        """Get cron access control settings."""
        allow = []
        deny = []
        if Path(CRON_ALLOW).exists():
            allow = [u.strip() for u in Path(CRON_ALLOW).read_text().splitlines() if u.strip()]
        if Path(CRON_DENY).exists():
            deny = [u.strip() for u in Path(CRON_DENY).read_text().splitlines() if u.strip()]
        return {"allow": allow, "deny": deny}

    # ── logging and audit ────────────────────────────────────────────
    def log_cron_event(self, event_type: str, username: str, command: str, result: str = "") -> Dict[str, Any]:
        """Log a cron event."""
        log_entry = {
            "timestamp": datetime.now().isoformat(),
            "type": event_type,
            "user": username,
            "command": command,
            "result": result,
        }
        with open(CRON_LOG, "a") as f:
            f.write(json.dumps(log_entry) + "\n")
        return {"action": "logged", "type": event_type}

    def read_cron_log(self, lines: int = 100) -> List[Dict[str, Any]]:
        """Read the last N lines from the cron log."""
        log_path = Path(CRON_LOG)
        if not log_path.exists():
            return []
        all_lines = log_path.read_text().strip().splitlines()
        entries = []
        for line in all_lines[-lines:]:
            try:
                entries.append(json.loads(line))
            except json.JSONDecodeError:
                entries.append({"raw": line})
        return entries

    # ── backup and export ────────────────────────────────────────────
    def backup_all(self, backup_path: Optional[Path] = None) -> Path:
        """Backup all cron configuration."""
        if backup_path is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            backup_path = Path(f"/var/backups/cron_{timestamp}.json")
        backup_path.parent.mkdir(parents=True, exist_ok=True)
        data = {
            "timestamp": datetime.now().isoformat(),
            "system_crontab": self.parse_system_crontab(),
            "user_crontabs": {u: self.parse_user_crontab(u) for u in self.list_user_crontabs()},
            "cron_d": self.list_cron_d(),
            "anacrontab": self.parse_anacrontab(),
            "at_jobs": self.list_at_jobs(),
            "batch_jobs": self.list_batch_jobs(),
        }
        backup_path.write_text(json.dumps(data, indent=2))
        return backup_path

    def export_status(self) -> Dict[str, Any]:
        """Export full cron system status."""
        return {
            "system_crontab": self.parse_system_crontab(),
            "user_crontabs": {u: self.parse_user_crontab(u) for u in self.list_user_crontabs()},
            "cron_d": self.list_cron_d(),
            "anacrontab": self.parse_anacrontab(),
            "at_jobs": self.list_at_jobs(),
            "batch_jobs": self.list_batch_jobs(),
            "access": self.get_cron_access(),
        }

    # ── internal helpers ──────────────────────────────────────────────
    def _parse_crontab_file(self, path: Path, is_system: bool = False) -> List[Dict[str, Any]]:
        """Parse a crontab file."""
        entries = []
        if not path.exists():
            return entries
        for line in path.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if line.startswith("SHELL=") or line.startswith("PATH=") or line.startswith("MAILTO="):
                continue
            parsed = self._parse_cron_entry(line, is_system)
            if parsed:
                entries.append(parsed)
        return entries

    def _parse_cron_entry(self, line: str, is_system: bool = False) -> Optional[Dict[str, Any]]:
        """Parse a single cron entry line."""
        if is_system:
            match = CRON_D_TIME_RE.match(line)
        else:
            match = CRON_TIME_RE.match(line)
        if not match:
            return None
        data = match.groupdict()
        result = {
            "minute": data.get("minute"),
            "hour": data.get("hour"),
            "day": data.get("day"),
            "month": data.get("month"),
            "weekday": data.get("weekday"),
            "command": data.get("command"),
            "raw": line,
        }
        if is_system:
            result["user"] = data.get("user", "root")
        return result

    def _parse_cron_d_entry(self, line: str) -> Optional[Dict[str, Any]]:
        """Parse a cron.d entry (must include user field)."""
        match = CRON_D_TIME_RE.match(line.strip())
        if not match:
            return None
        data = match.groupdict()
        return {
            "minute": data.get("minute"),
            "hour": data.get("hour"),
            "day": data.get("day"),
            "month": data.get("month"),
            "weekday": data.get("weekday"),
            "user": data.get("user"),
            "command": data.get("command"),
            "raw": line.strip(),
        }

    def _parse_anacrontab_file(self, path: Path) -> List[Dict[str, Any]]:
        """Parse anacrontab."""
        entries = []
        if not path.exists():
            return entries
        for line in path.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            match = ANACRON_RE.match(line)
            if match:
                data = match.groupdict()
                entries.append({
                    "period": data.get("period"),
                    "delay": data.get("delay", "0"),
                    "job_id": data.get("job_id"),
                    "command": data.get("command"),
                })
        return entries

    def _list_cron_dir(self, d: Path) -> List[Dict[str, Any]]:
        """List all scripts in a cron directory with details."""
        results = []
        if not d.exists():
            return results
        for item in d.iterdir():
            if item.is_file():
                stat = item.stat()
                results.append({
                    "name": item.name,
                    "path": str(item),
                    "size": stat.st_size,
                    "mode": oct(stat.st_mode),
                    "owner": self._get_file_owner(item),
                })
        return results

    def _list_spool_jobs(self, spool_dir: str) -> List[Dict[str, Any]]:
        """List jobs from a spool directory."""
        results = []
        d = Path(spool_dir)
        if not d.exists():
            return results
        for item in d.iterdir():
            if item.is_file():
                try:
                    data = json.loads(item.read_text())
                    results.append(data)
                except json.JSONDecodeError:
                    results.append({"name": item.name, "raw": item.read_text()[:200]})
        return results

    def _get_file_owner(self, path: Path) -> str:
        """Get the owner of a file."""
        try:
            import pwd
            return pwd.getpwuid(path.stat().st_uid).pw_name
        except (ImportError, KeyError):
            return "unknown"
