"""
Umer OS /compatibility/winerror — Windows error codes
=====================================================

The Microsoft Windows error model exposes two parallel code spaces:

* ``HRESULT``  (32-bit, returned by COM / WinRT and the higher-layer
  Win32 API).  Severity bits in the top word: ``SEVERITY_ERROR``
  (``0x80000000``) for failures, ``SEVERITY_SUCCESS`` (``0x00000000``)
  for success.

* ``LSTATUS`` / ``GetLastError()`` (32-bit "Win32" error code, returned
  by most C-style Win32 calls in kernel32 / user32 / advapi32 / etc.).
  ``winerror.h`` is the canonical source.

This module is a pure-Python reference of the most commonly-seen
values, designed to be imported by Umer OS's pure-Python Windows
compatibility layer.  Where a value depends on the Windows SDK
version we pick the longest-standing definition; where the value is
missing we return ``ERROR_SUCCESS`` / ``S_OK`` rather than guessing.

References
----------

* https://learn.microsoft.com/en-us/windows/win32/seccrypto/common-hresult-values
* https://learn.microsoft.com/en-us/windows/win32/debug/system-error-codes
* https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-erref

Author:  Umer OS Project
Licence: GPL-3.0
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Severity / facility helpers
# ---------------------------------------------------------------------------

SEVERITY_SUCCESS = 0x00000000
SEVERITY_ERROR = 0x80000000
SEVERITY_MASK = 0xC0000000  # both bits set = "WIN32" error category
FACILITY_MASK = 0x0FFF0000


def severity(hr: int) -> int:
    """Return the severity bits of an HRESULT."""
    return hr & SEVERITY_MASK


def facility(hr: int) -> int:
    """Return the facility bits of an HRESULT."""
    return hr & FACILITY_MASK


def make_hresult(facility: int, code: int) -> int:
    """Build an HRESULT with the given facility and error code."""
    severity_bits = SEVERITY_ERROR if code else SEVERITY_SUCCESS
    return severity_bits | (facility << 16) | (code & 0xFFFF)


def failed(hr: int) -> bool:
    """Return True if the HRESULT indicates failure (SEVERITY_ERROR set)."""
    return (hr & SEVERITY_ERROR) != 0


# ---------------------------------------------------------------------------
# Generic HRESULT values
# ---------------------------------------------------------------------------

S_OK = 0x00000000
S_FALSE = 0x00000001
E_NOTIMPL = 0x80004001
E_NOINTERFACE = 0x80004002
E_POINTER = 0x80004003
E_INVALIDARG = 0x80070057
E_OUTOFMEMORY = 0x8007000E
E_FAIL = 0x80004005
E_HANDLE = 0x80070006
E_ACCESSDENIED = 0x80070005
E_INVALIDHANDLE = 0x80070006
E_NOT_FOUND = 0x80070490
E_FAIL_TO_CREATE_PROCESS = 0x800700E8
E_PIPE_NOT_CONNECTED = 0x800700E9
E_PIPE_BUSY = 0x800700E7
E_NOT_ENOUGH_QUOTA = 0x8007051B

HRESULT_FROM_WIN32 = 0x80070000  # OR with a Win32 error to make HRESULT


def hresult_from_win32(err: int) -> int:
    """Convert a Win32 error code to the equivalent HRESULT."""
    return HRESULT_FROM_WIN32 | (err & 0xFFFF)


# ---------------------------------------------------------------------------
# Generic Win32 / GetLastError codes (subset of winerror.h)
# ---------------------------------------------------------------------------

ERROR_SUCCESS = 0
ERROR_INVALID_FUNCTION = 1
ERROR_FILE_NOT_FOUND = 2
ERROR_PATH_NOT_FOUND = 3
ERROR_TOO_MANY_OPEN_FILES = 4
ERROR_ACCESS_DENIED = 5
ERROR_INVALID_HANDLE = 6
ERROR_ARENA_TRASHED = 7
ERROR_NOT_ENOUGH_MEMORY = 8
ERROR_INVALID_BLOCK = 9
ERROR_BAD_ENVIRONMENT = 10
ERROR_BAD_FORMAT = 11
ERROR_INVALID_ACCESS = 12
ERROR_INVALID_DATA = 13
ERROR_OUTOFMEMORY = 14
ERROR_INVALID_DRIVE = 15
ERROR_CURRENT_DIRECTORY = 16
ERROR_NOT_SAME_DEVICE = 17
ERROR_NO_MORE_FILES = 18
ERROR_WRITE_PROTECT = 19
ERROR_BAD_UNIT = 20
ERROR_NOT_READY = 21
ERROR_BAD_COMMAND = 22
ERROR_CRC = 23
ERROR_BAD_LENGTH = 24
ERROR_SEEK = 25
ERROR_NOT_DOS_DISK = 26
ERROR_SECTOR_NOT_FOUND = 27
ERROR_OUT_OF_PAPER = 28
ERROR_WRITE_FAULT = 29
ERROR_READ_FAULT = 30
ERROR_GEN_FAILURE = 31
ERROR_SHARING_VIOLATION = 32
ERROR_LOCK_VIOLATION = 33
ERROR_WRONG_DISK = 34
ERROR_SHARING_BUFFER_EXCEEDED = 36
ERROR_HANDLE_EOF = 38
ERROR_HANDLE_DISK_FULL = 39
ERROR_NOT_SUPPORTED = 50
ERROR_REM_NOT_LIST = 51
ERROR_DUP_NAME = 52
ERROR_BAD_NETPATH = 53
ERROR_NETWORK_BUSY = 54
ERROR_DEV_NOT_EXIST = 55
ERROR_TOO_MANY_CMDS = 56
ERROR_ADAP_HDW_ERR = 57
ERROR_BAD_NET_RESP = 58
ERROR_UNEXP_NET_ERR = 59
ERROR_BAD_REM_ADAP = 60
ERROR_PRINTQ_FULL = 61
ERROR_NO_SPOOL_SPACE = 62
ERROR_PRINT_CANCELLED = 63
ERROR_NETNAME_DELETED = 64
ERROR_NET_ACCESS_DENIED = 65
ERROR_BAD_DEV_TYPE = 66
ERROR_BAD_NET_NAME = 67
ERROR_TOO_MANY_NAMES = 68
ERROR_TOO_MANY_SESS = 69
ERROR_SHARING_PAUSED = 70
ERROR_REQ_NOT_ACCEP = 71
ERROR_REDIR_PAUSED = 72
ERROR_FILE_EXISTS = 80
ERROR_CANNOT_MAKE = 82
ERROR_FAIL_I24 = 83
ERROR_OUT_OF_STRUCTURES = 84
ERROR_ALREADY_ASSIGNED = 85
ERROR_INVALID_PASSWORD = 86
ERROR_INVALID_PARAMETER = 87
ERROR_NET_WRITE_FAULT = 88
ERROR_NET_READ_FAULT = 89
ERROR_TOO_MANY_TARGETS = 90
ERROR_NO_PROC_SLOTS = 91
ERROR_TIMER_RES_NOT_SET = 92
ERROR_QUEUE_FULL = 93
ERROR_NO_MORE_ITEMS = 94
ERROR_CANNOT_COPY = 95
ERROR_FILE_NOT_FOUND_2 = 98
ERROR_INVALID_DRIVE_2 = 99
ERROR_NO_PROC_TIMEOUTS = 100
ERROR_INVALID_TARGET_HANDLE = 101
ERROR_INVALID_USER_BUFFER = 1784
ERROR_INVALID_NAME = 123
ERROR_PROC_NOT_FOUND = 127
ERROR_WAIT_NO_CHILDREN = 128
ERROR_CHILD_NOT_COMPLETE = 129
ERROR_DIRECT_ACCESS_HANDLE = 130
ERROR_NEGATIVE_SEEK = 131
ERROR_SEEK_ON_DEVICE = 132
ERROR_IS_JOIN_TARGET = 133
ERROR_IS_JOINED = 134
ERROR_IS_SUBSTED = 135
ERROR_NOT_JOINED = 136
ERROR_NOT_SUBSTED = 137
ERROR_JOIN_TO_JOIN = 138
ERROR_SUBST_TO_SUBST = 139
ERROR_JOIN_TO_SUBST = 140
ERROR_SUBST_TO_JOIN = 141
ERROR_BUSY_DRIVE = 142
ERROR_SAME_DRIVE = 143
ERROR_DIR_NOT_ROOT = 144
ERROR_DIR_NOT_EMPTY = 145
ERROR_IS_REDIRECTED = 146
ERROR_DM_BUFFER_TOO_SMALL = 147
ERROR_LABEL_TOO_LONG = 148
ERROR_BAD_PATHNAME = 149
ERROR_PATH_BUSY = 150
ERROR_IS_SUBST_PATH = 151
ERROR_IS_JOIN_PATH = 152
ERROR_PATH_BUSY_2 = 153
ERROR_BUSY = 170
ERROR_ALREADY_EXISTS = 183
ERROR_ENVVAR_NOT_FOUND = 203
ERROR_FILENAME_EXCED_RANGE = 206
ERROR_MORE_DATA = 234
ERROR_NO_MORE_ITEMS_2 = 259
ERROR_SERVICE_ALREADY_RUNNING = 1056
ERROR_SERVICE_NOT_ACTIVE = 1062
ERROR_SERVICE_DISABLED = 1058
ERROR_SERVICE_NOT_FOUND = 1243
ERROR_SERVICE_NOT_STARTED = 1057
ERROR_SERVICE_START_PENDING = 1058
ERROR_SERVICE_STOP_PENDING = 1059
ERROR_SERVICE_STOP = 1054
ERROR_SERVICE_EXISTS = 1073
ERROR_SERVICE_CANNOT_ACCEPT_CTRL = 1061
ERROR_SERVICE_NO_THREAD = 1059
ERROR_SERVICE_DATABASE_LOCKED = 1052
ERROR_SERVICE_DEPENDENCY_DELETED = 1075
ERROR_SERVICE_DEPENDENCY_FAIL = 1068
ERROR_SERVICE_DISABLED_2 = 1058
ERROR_SERVICE_LOGON_FAILED = 1069
ERROR_SERVICE_START_HANG = 1070
ERROR_INVALID_SERVICE_ACCOUNT = 1057
ERROR_SERVICE_MARKED_FOR_DELETE = 1072
ERROR_INVALID_HANDLE_STATE = 3021
ERROR_NOT_ENOUGH_PRIVILEGES = 1314
ERROR_PRIVILEGE_NOT_HELD = 1314
ERROR_LOGON_FAILURE = 1326
ERROR_ACCOUNT_RESTRICTION = 1327
ERROR_ACCESS_DENIED_2 = 5
ERROR_NO_SUCH_USER = 1317
ERROR_PASSWORD_RESTRICTION = 1325
ERROR_PASSWORD_EXPIRED = 1330
ERROR_ACCOUNT_DISABLED = 1331
ERROR_NONE_MAPPED = 1332
ERROR_TRUSTED_RELATIONSHIP_FAILURE = 1790
ERROR_TRUSTED_DOMAIN_FAILURE = 1791
ERROR_TRUST_FAILURE = 1792
ERROR_NETLOGON_NOT_STARTED = 1792
ERROR_ACCOUNT_EXPIRED = 1331
ERROR_UNKNOWN_REVISION = 1305
ERROR_REVISION_MISMATCH = 1306
ERROR_INVALID_OWNER = 1307
ERROR_INVALID_PRIMARY_GROUP = 1308
ERROR_NO_IMPERSONATION_TOKEN = 1309
ERROR_CANT_DISABLE_MANDATORY = 1310
ERROR_NO_SUCH_LOGON_SESSION = 1313
ERROR_NO_SUCH_PRIVILEGE = 1313
ERROR_PRIVILEGE_NOT_HELD_2 = 1314
ERROR_INVALID_ACCOUNT_NAME = 1315
ERROR_USER_EXISTS = 1316
ERROR_NO_SUCH_USER_2 = 1317
ERROR_GROUP_EXISTS = 1318
ERROR_NO_SUCH_GROUP = 1319
ERROR_MEMBER_IN_GROUP = 1320
ERROR_MEMBER_NOT_IN_GROUP = 1321
ERROR_LAST_ADMIN = 1322
ERROR_WRONG_PASSWORD = 1323
ERROR_ILL_FORMED_PASSWORD = 1324
ERROR_PASSWORD_RESTRICTION_2 = 1325
ERROR_LOGON_FAILURE_2 = 1326
ERROR_ACCOUNT_RESTRICTION_2 = 1327
ERROR_INVALID_LOGON_HOURS = 1328
ERROR_INVALID_LOGON_TYPE = 1329
ERROR_PASSWORD_EXPIRED_2 = 1330
ERROR_ACCOUNT_DISABLED_2 = 1331
ERROR_NONE_MAPPED_2 = 1332
ERROR_RESOURCE_TYPE_NOT_FOUND = 1812
ERROR_RESOURCE_NAME_NOT_FOUND = 1804
ERROR_RESOURCE_LANG_NOT_FOUND = 1815
ERROR_NOT_ENOUGH_QUOTA_2 = 1816
ERROR_INVALID_SUBJECT = 1335
ERROR_INVALID_DOMAIN_ROLE = 1351
ERROR_NO_SUCH_DOMAIN = 1352
ERROR_DOMAIN_EXISTS = 1353
ERROR_DOMAIN_LIMIT_EXCEEDED = 1354
ERROR_INTERNAL_DB_ERROR = 1355
ERROR_INTERNAL_ERROR = 1356
ERROR_DOMAIN_NOT_FOUND = 1357
ERROR_USER_NOT_FOUND = 1358

# --- File / I/O error codes (subset) -------------------------------------

ERROR_FILE_NOT_FOUND_3 = ERROR_FILE_NOT_FOUND
ERROR_PATH_NOT_FOUND_2 = ERROR_PATH_NOT_FOUND
ERROR_ACCESS_DENIED_3 = ERROR_ACCESS_DENIED
ERROR_INVALID_NAME_2 = ERROR_INVALID_NAME
ERROR_FILENAME_EXCED_RANGE_2 = ERROR_FILENAME_EXCED_RANGE
ERROR_SHARING_VIOLATION_2 = ERROR_SHARING_VIOLATION
ERROR_LOCK_VIOLATION_2 = ERROR_LOCK_VIOLATION
ERROR_HANDLE_DISK_FULL_2 = ERROR_HANDLE_DISK_FULL
ERROR_DISK_FULL = 112
ERROR_HANDLE_EOF_2 = ERROR_HANDLE_EOF
ERROR_BROKEN_PIPE = 109
ERROR_PIPE_NOT_CONNECTED_2 = 233
ERROR_PIPE_BUSY_2 = ERROR_PIPE_BUSY
ERROR_PRIVILEGE_NOT_HELD_3 = ERROR_PRIVILEGE_NOT_HELD

# --- Registry / object manager codes (subset) ----------------------------

ERROR_REGISTRY_RECOVERED = 1014
ERROR_REGISTRY_CORRUPT = 1015
ERROR_REGISTRY_IO_FAILED = 1016
ERROR_NOT_REGISTRY_FILE = 1017
ERROR_KEY_DELETED = 1018
ERROR_CANTOPEN_ANONYMOUS = 1307
ERROR_CANT_OPEN_USER_TOKEN = 1308
ERROR_CANT_LOAD_CLASS = 1309
ERROR_NO_TOKEN = 1310
ERROR_REGISTRY_HIVE_RECOVERED = 1014
ERROR_REGISTRY_HIVE_CORRUPT = 1015
ERROR_REGISTRY_IO_FAILED_2 = ERROR_REGISTRY_IO_FAILED
ERROR_KEY_HAS_CHILDREN = 1020
ERROR_CHILD_MUST_BE_VOLATILE = 1021
ERROR_CHILD_ALREADY_HAS_PARENT = 1022
ERROR_CHILD_WINDOWLESS_PARENT = 1023
ERROR_CHILD_ALREADY_HAS_THIS_PARENT = 1024
ERROR_CANT_CREATE_CLASS = 1311
ERROR_CANT_LOAD_CLASS_2 = 1309

# --- Generic convenience -------------------------------------------------

#: A small but commonly-used subset (extracted by name into a single
#: dict for fast lookup from error-handling code).
WIN32_ERROR_NAMES: Dict[int, str] = {
    v: k
    for k, v in globals().items()
    if k.startswith("ERROR_") and isinstance(v, int)
}


def format_win32_error(err: int) -> str:
    """Return a human-readable label for a Win32 error code (or hex fallback)."""
    name = WIN32_ERROR_NAMES.get(err)
    if name is not None:
        return f"{name} (0x{err:08X})"
    return f"0x{err:08X}"


def format_hresult(hr: int) -> str:
    """Return a human-readable label for an HRESULT."""
    if hr == S_OK:
        return "S_OK"
    if hr == S_FALSE:
        return "S_FALSE"
    if hr == E_NOTIMPL:
        return "E_NOTIMPL"
    if hr == E_POINTER:
        return "E_POINTER"
    if hr == E_INVALIDARG:
        return "E_INVALIDARG"
    if hr == E_OUTOFMEMORY:
        return "E_OUTOFMEMORY"
    if hr == E_FAIL:
        return "E_FAIL"
    if (hr & HRESULT_FROM_WIN32) == HRESULT_FROM_WIN32:
        win = hr & 0xFFFF
        return f"HRESULT_FROM_WIN32({format_win32_error(win)})"
    fac = facility(hr) >> 16
    code = hr & 0xFFFF
    return f"HRESULT(facility=0x{fac:04X}, code=0x{code:04X})"
