# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""QRNG — Quantum Random Number Generator.

Implements true random number generation using quantum circuits.
"""

from __future__ import annotations

import math
import hashlib
import secrets
from dataclasses import dataclass
from typing import Optional, List, Tuple

from .circuit import QuantumCircuit, QuantumRegister, ClassicalRegister
from .simulator import StatevectorSimulator
from .backend import LocalBackend


# ---------------------------------------------------------------------------
# Result Types
# ---------------------------------------------------------------------------

@dataclass
class RandomBit:
    """A single random bit."""
    value: int
    circuit_depth: int
    basis: str = "computational"

    def __int__(self) -> int:
        return self.value

    def __bool__(self) -> bool:
        return bool(self.value)

    def __repr__(self) -> str:
        return f"RandomBit({self.value})"


@dataclass
class RandomBytes:
    """Random byte sequence."""
    data: bytes
    num_bits: int
    method: str

    def hex(self) -> str:
        return self.data.hex()

    def int(self) -> int:
        return int.from_bytes(self.data, 'big')

    def bits(self) -> List[int]:
        return [int(b) for b in format(self.int(), f'0{self.num_bits}b')]

    def __len__(self) -> int:
        return len(self.data)

    def __repr__(self) -> str:
        return f"RandomBytes({len(self.data)} bytes, method={self.method})"


# ---------------------------------------------------------------------------
# Core QRNG
# ---------------------------------------------------------------------------

class QRNG:
    """Quantum Random Number Generator.

    Uses quantum circuits to generate true random numbers
    based on quantum mechanical principles.
    """

    def __init__(self, backend: Optional[LocalBackend] = None,
                 seed: Optional[int] = None):
        """Initialize QRNG.

        Args:
            backend: Optional backend for simulation
            seed: Optional seed for reproducibility
        """
        self._backend = backend
        self._seed = seed
        self._count = 0

    def _run_circuit(self, circuit: QuantumCircuit) -> dict:
        """Run a circuit and return measurement results."""
        backend = self._backend or LocalBackend()
        result = backend.run(circuit, shots=1)
        return result.counts

    def random_bit(self) -> RandomBit:
        """Generate a single random bit.

        Returns:
            RandomBit with 0 or 1
        """
        qr = QuantumRegister(1, "q")
        cr = ClassicalRegister(1, "c")
        circuit = QuantumCircuit(qr, cr)

        # Create superposition
        circuit.h(qr[0])
        circuit.measure(qr[0], cr[0])

        counts = self._run_circuit(circuit)
        bit = int(list(counts.keys())[0], 2)
        self._count += 1

        return RandomBit(
            value=bit,
            circuit_depth=circuit.depth,
            basis="computational"
        )

    def random_bits(self, n: int) -> List[int]:
        """Generate multiple random bits.

        Args:
            n: Number of bits to generate

        Returns:
            List of random bits
        """
        bits = []
        for _ in range(n):
            bits.append(self.random_bit().value)
        return bits

    def random_int(self, bits: int = 32) -> int:
        """Generate a random integer.

        Args:
            bits: Number of bits for the integer

        Returns:
            Random integer
        """
        random_bits = self.random_bits(bits)
        result = 0
        for bit in random_bits:
            result = (result << 1) | bit
        return result

    def random_float(self) -> float:
        """Generate a random float between 0 and 1.

        Returns:
            Random float in [0, 1)
        """
        # Use 64 bits for precision
        random_bits = self.random_bits(64)
        value = 0
        for bit in random_bits:
            value = (value << 1) | bit
        return value / (2 ** 64)

    def random_bytes(self, num_bytes: int) -> RandomBytes:
        """Generate random bytes.

        Args:
            num_bytes: Number of bytes to generate

        Returns:
            RandomBytes with the generated bytes
        """
        byte_array = bytearray()
        for _ in range(num_bytes):
            byte_bits = self.random_bits(8)
            byte_val = 0
            for bit in byte_bits:
                byte_val = (byte_val << 1) | bit
            byte_array.append(byte_val)

        self._count += num_bytes * 8

        return RandomBytes(
            data=bytes(byte_array),
            num_bits=num_bytes * 8,
            method="quantum_hadamard"
        )

    def random_string(self, length: int) -> str:
        """Generate a random alphanumeric string.

        Args:
            length: Length of the string

        Returns:
            Random alphanumeric string
        """
        chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
        indices = [self.random_int(6) % len(chars) for _ in range(length)]
        return "".join(chars[i] for i in indices)

    def coin_flip(self) -> bool:
        """Simulate a fair coin flip.

        Returns:
            True or False
        """
        return bool(self.random_bit().value)


# ---------------------------------------------------------------------------
# Quantum Entropy Source
# ---------------------------------------------------------------------------

class QuantumEntropy:
    """Quantum entropy source for cryptographic applications.

    Uses quantum circuits to extract high-quality randomness
    suitable for cryptographic key generation.
    """

    def __init__(self, num_qubits: int = 8, backend: Optional[LocalBackend] = None):
        """Initialize quantum entropy source.

        Args:
            num_qubits: Number of qubits for entropy generation
            backend: Optional backend
        """
        self._num_qubits = num_qubits
        self._backend = backend
        self._pool = bytearray()
        self._qrng = QRNG(backend)

    def _extract_entropy(self) -> bytes:
        """Extract entropy from quantum measurements."""
        qr = QuantumRegister(self._num_qubits, "q")
        cr = ClassicalRegister(self._num_qubits, "c")
        circuit = QuantumCircuit(qr, cr)

        # Apply Hadamard to all qubits for maximum entropy
        for q in range(self._num_qubits):
            circuit.h(qr[q])

        # Add random rotations for additional randomness
        for q in range(self._num_qubits):
            circuit.ry(self._qrng.random_float() * 2 * math.pi, qr[q])

        circuit.measure(qr, cr)

        backend = self._backend or LocalBackend()
        result = backend.run(circuit, shots=1)
        key = list(result.counts.keys())[0]

        # Convert bitstring to bytes
        return int(key, 2).to_bytes((self._num_qubits + 7) // 8, 'big')

    def seed(self, entropy: bytes) -> None:
        """Seed the entropy pool.

        Args:
            entropy: Entropy bytes to add
        """
        self._pool.extend(entropy)

    def get_random_bytes(self, num_bytes: int) -> bytes:
        """Get random bytes, mixing quantum and classical entropy.

        Args:
            num_bytes: Number of bytes to generate

        Returns:
            Random bytes
        """
        result = bytearray()

        # Mix quantum entropy
        while len(result) < num_bytes:
            quantum_entropy = self._extract_entropy()
            for b in quantum_entropy:
                if len(result) < num_bytes:
                    result.append(b)

        return bytes(result)


# ---------------------------------------------------------------------------
# Bias Testing
# ---------------------------------------------------------------------------

def test_randomness_bias(bits: List[int], confidence: float = 0.05) -> dict:
    """Test for bias in random bit sequence.

    Args:
        bits: List of random bits (0s and 1s)
        confidence: Confidence level for test

    Returns:
        Dictionary with test results
    """
    n = len(bits)
    if n == 0:
        return {"error": "No bits provided"}

    ones = sum(bits)
    zeros = n - ones
    ratio = ones / n

    # Expected ratio under null hypothesis
    expected_ratio = 0.5
    expected_ones = n * expected_ratio

    # Chi-square test
    chi_square = ((ones - expected_ones) ** 2 / expected_ones +
                  (zeros - expected_ones) ** 2 / expected_ones)

    # Simple threshold (chi-square with 1 df)
    threshold = 3.841

    return {
        "num_bits": n,
        "num_ones": ones,
        "num_zeros": zeros,
        "ratio": ratio,
        "chi_square": chi_square,
        "threshold": threshold,
        "is_random": chi_square < threshold,
        "bias": abs(ratio - 0.5),
    }


def test_entropy_rate(bits: List[int], block_size: int = 8) -> dict:
    """Estimate entropy rate of bit sequence.

    Args:
        bits: List of random bits
        block_size: Block size for analysis

    Returns:
        Dictionary with entropy estimates
    """
    n = len(bits)
    if n < block_size:
        return {"error": "Not enough bits"}

    # Count unique blocks
    blocks = {}
    for i in range(0, n - block_size + 1, block_size):
        block = tuple(bits[i:i + block_size])
        blocks[block] = blocks.get(block, 0) + 1

    num_blocks = len(blocks)
    total_blocks = sum(blocks.values())

    # Calculate Shannon entropy
    entropy = 0.0
    for count in blocks.values():
        p = count / total_blocks
        if p > 0:
            entropy -= p * math.log2(p)

    max_entropy = math.log2(num_blocks) if num_blocks > 0 else 0

    return {
        "num_bits": n,
        "block_size": block_size,
        "unique_blocks": num_blocks,
        "entropy_per_block": entropy,
        "entropy_per_bit": entropy / block_size,
        "max_entropy_per_bit": max_entropy / block_size,
        "efficiency": entropy / max_entropy if max_entropy > 0 else 0,
    }


# ---------------------------------------------------------------------------
# Convenience Functions
# ---------------------------------------------------------------------------

def generate_random_bit(backend: Optional[LocalBackend] = None) -> bool:
    """Generate a single random bit.

    Args:
        backend: Optional backend

    Returns:
        True or False
    """
    qrng = QRNG(backend)
    return qrng.coin_flip()


def generate_random_int(bits: int = 32,
                        backend: Optional[LocalBackend] = None) -> int:
    """Generate a random integer.

    Args:
        bits: Number of bits
        backend: Optional backend

    Returns:
        Random integer
    """
    qrng = QRNG(backend)
    return qrng.random_int(bits)


def generate_random_bytes(num_bytes: int,
                          backend: Optional[LocalBackend] = None) -> bytes:
    """Generate random bytes.

    Args:
        num_bytes: Number of bytes
        backend: Optional backend

    Returns:
        Random bytes
    """
    qrng = QRNG(backend)
    return qrng.random_bytes(num_bytes).data


def generate_random_string(length: int,
                           backend: Optional[LocalBackend] = None) -> str:
    """Generate a random string.

    Args:
        length: String length
        backend: Optional backend

    Returns:
        Random alphanumeric string
    """
    qrng = QRNG(backend)
    return qrng.random_string(length)


# ---------------------------------------------------------------------------
# Export
# ---------------------------------------------------------------------------

__all__ = [
    "RandomBit",
    "RandomBytes",
    "QRNG",
    "QuantumEntropy",
    "test_randomness_bias",
    "test_entropy_rate",
    "generate_random_bit",
    "generate_random_int",
    "generate_random_bytes",
    "generate_random_string",
]
