"""
UmerOS /sbin Module Commands
==============================
Kernel module management command implementations.
insmod, lsmod, modprobe, rmmod
"""

from __future__ import annotations
import os
import sys
from abc import abstractmethod
from typing import Any, Dict, List, Optional


class SbinCommand:
    """Base class for /sbin commands."""

    name: str = ""
    description: str = ""
    usage: str = ""

    @abstractmethod
    def execute(self, args: Optional[List[str]] = None) -> int:
        pass

    def help(self) -> str:
        return f"Usage: {self.usage}\n{self.description}"


# ─── Module Commands ─────────────────────────────────────────────────────────

class InsmodCommand(SbinCommand):
    """Insert a module into the kernel."""
    name = "insmod"
    description = "Insert a module into the kernel"
    usage = "insmod [filename] [module-parameters]"

    def execute(self, args: Optional[List[str]] = None) -> int:
        if not args:
            print("insmod: missing module filename", file=sys.stderr)
            return 1
        module = args[0]
        print(f"[*] insmod: inserting module '{module}'")
        return 0


class LsmodCommand(SbinCommand):
    """List currently loaded kernel modules."""
    name = "lsmod"
    description = "Show the status of modules in the kernel"
    usage = "lsmod"

    def execute(self, args: Optional[List[str]] = None) -> int:
        print("Module                  Size  Used by")
        print("vfio_pci               81920  0")
        print("irqbypass              16384  1 vfio_pci")
        print("kvm_intel             401408  0")
        print("kvm                   983040  1 kvm_intel")
        print("pcspkr                 16384  0")
        print("i2c_piix4             28672  0")
        print("joydev                 24576  0")
        print("input_leds             16384  0")
        print("serio_raw              20480  0")
        print("ext4                  917504  1")
        print("mbcache                16384  1 ext4")
        print("jbd2                  106496  1 ext4")
        return 0


class ModprobeCommand(SbinCommand):
    """Add or remove modules from the kernel."""
    name = "modprobe"
    description = "Intelligently add or remove modules from the kernel"
    usage = "modprobe [-k] [-r] [-v] module-name"

    def execute(self, args: Optional[List[str]] = None) -> int:
        if not args:
            print("modprobe: missing module name", file=sys.stderr)
            return 1

        module = args[0]
        remove = "-r" in args

        if remove:
            print(f"[*] modprobe: removing module '{module}'")
        else:
            print(f"[*] modprobe: loading module '{module}'")
        return 0


class RmmodCommand(SbinCommand):
    """Remove a module from the kernel."""
    name = "rmmod"
    description = "Remove a module from the kernel"
    usage = "rmmod [-f] [-w] [-s] module-name"

    def execute(self, args: Optional[List[str]] = None) -> int:
        if not args:
            print("rmmod: missing module name", file=sys.stderr)
            return 1
        module = args[0]
        print(f"[*] rmmod: removing module '{module}'")
        return 0


class DepmodCommand(SbinCommand):
    """Generate module dependency file (modules.dep)."""
    name = "depmod"
    description = "Generate a module dependency file for the kernel module loader"
    usage = "depmod [-a] [-e] [-F System.map] [-n] [-v] [version]"

    def execute(self, args: Optional[List[str]] = None) -> int:
        analyze = "-a" in args
        version = None

        # Get kernel version if provided
        for arg in (args or []):
            if not arg.startswith("-"):
                version = arg
                break

        if not version:
            import platform
            version = platform.release()

        if analyze:
            print(f"depmod: analyzing modules for version {version}")
        else:
            print(f"depmod: generating module dependency map for {version}")

        # Simulate writing modules.dep
        modules = [
            "kernel/drivers/net/e1000/e1000.ko",
            "kernel/drivers/usb/core/usbcore.ko",
            "kernel/fs/ext4/ext4.ko",
            "kernel/net/ipv4/tcp_ipv4.ko",
            "kernel/drivers/block/virtio_blk.ko",
        ]

        print(f"# modules.dep generated by depmod for {version}")
        for mod in modules:
            deps = "kernel/drivers/virtio/virtio.ko" if "virtio" in mod else ""
            print(f"{mod}: {deps}".rstrip())

        print(f"depmod: written /lib/modules/{version}/modules.dep")
        return 0
