from typing import Protocol, runtime_checkable, Dict, Any

# Global registry for character devices
CHAR_DEVICES: Dict[str, Any] = {}

@runtime_checkable
class FileOperations(Protocol):
    """Mimic file_operations for character devices."""
    def open(self, mode: str = "r") -> None: ...
    def read(self, size: int = -1) -> str: ...
    def write(self, data: str) -> int: ...
    def release(self) -> None: ...
