"""
Umer OS /root - dotfiles manager
================================
Manages the dotfiles inside root's home directory.

/root page does not mandate specific dotfiles - those are
distribution choice - but in practice every Linux root account ships
with the following:

* ``.bashrc``        - interactive non-login shell init
* ``.bash_profile``  - login shell init (often sources ``.bashrc``)
* ``.profile``       - POSIX-compatible login shell init
* ``.bash_logout``   - cleanup on login shell exit
* ``.forward``       - mail forwarding (per the TLDP requirement)
* ``.bash_history``  - command history (root must not leak)
* ``.vimrc``         - editor defaults

UmerOS is a fresh project so this module models the *policy* and
provides a templating mechanism.  Operators can drop in their own
templates via :func:`register_template`; the rest of the runtime
just calls :meth:`RootDotfilesManager.ensure_all` to materialise
them.

Security note: root's history file is sensitive and we tighten its
permissions to ``0600`` on creation.

Author:  Umer OS Project
Licence: Apache 2.0
"""

from __future__ import annotations

import datetime as _dt
import logging
import os
import stat
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, Dict, List, Optional

log = logging.getLogger("UmerOS.Root.Dotfiles")


# ---------------------------------------------------------------------------
# Default templates
# ---------------------------------------------------------------------------

BASHRC_TEMPLATE = """\
# Umer OS /root/.bashrc - interactive non-login shell init
# Generated by /root package on {generated_at}

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# History controls
HISTCONTROL=ignoreboth
HISTSIZE=2000
HISTFILESIZE=5000
shopt -s histappend

# Update window size after every command
shopt -s checkwinsize

# Make less friendly for non-text input files
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# Prompt - red '#' makes it visually obvious we are root.
PS1='\\\\u@\\\\h:\\\\w# '

# Aliases (defensive defaults)
alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Enable programmable completion
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi
"""

BASH_PROFILE_TEMPLATE = """\
# Umer OS /root/.bash_profile - login shell init
# Generated by /root package on {generated_at}

# Source .bashrc if it exists
if [ -f "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
fi

# Set PATH so /usr/local/sbin and /sbin come first
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
"""

PROFILE_TEMPLATE = """\
# Umer OS /root/.profile - POSIX-compatible login shell init
# Generated by /root package on {generated_at}

# Set PATH
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# Source .bashrc if available
if [ -n "$BASH_VERSION" ] && [ -f "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
fi

# Mail forwarding - admin mail should go to a non-root user.
# Override by setting $MAIL_TO before login.
if [ -z "$MAIL_TO" ] && [ -f "$HOME/.forward" ]; then
    export MAIL_TO="$(cat "$HOME/.forward" | head -n1)"
fi
"""

BASH_LOGOUT_TEMPLATE = """\
# Umer OS /root/.bash_logout - login shell cleanup
# Generated by /root package on {generated_at}

# Clear the screen on logout for security
if [ "$SHLVL" = 1 ]; then
    [ -x /usr/bin/clear_console ] && /usr/bin/clear_console -q
fi
"""

VIMRC_TEMPLATE = """\
" Umer OS /root/.vimrc
" Generated by /root package on {generated_at}

syntax on
set showmode
set showcmd
set ignorecase
set smartcase
set autoindent
set expandtab
set tabstop=4
set shiftwidth=4
" History limit
set history=200
" Do not keep backup files in the root home directory
set nobackup
set nowritebackup
"""

DEFAULT_TEMPLATES: Dict[str, str] = {
    ".bashrc":       BASHRC_TEMPLATE,
    ".bash_profile": BASH_PROFILE_TEMPLATE,
    ".profile":      PROFILE_TEMPLATE,
    ".bash_logout":  BASH_LOGOUT_TEMPLATE,
    ".vimrc":        VIMRC_TEMPLATE,
}


# ---------------------------------------------------------------------------
# Result dataclass
# ---------------------------------------------------------------------------

@dataclass
class DotfileResult:
    """The outcome of materialising one dotfile."""

    name: str
    path: str
    created: bool
    updated: bool
    mode: int
    size_bytes: int
    note: str = ""

    def as_dict(self) -> dict:
        return {
            "name":        self.name,
            "path":        self.path,
            "created":     self.created,
            "updated":     self.updated,
            "mode":        oct(self.mode),
            "size_bytes":  self.size_bytes,
            "note":        self.note,
        }


@dataclass
class DotfilesReport:
    """The aggregate result of :meth:`RootDotfilesManager.ensure_all`."""

    home: str
    results: List[DotfileResult] = field(default_factory=list)
    issues: List[str] = field(default_factory=list)

    def as_dict(self) -> dict:
        return {
            "home":    self.home,
            "results": [r.as_dict() for r in self.results],
            "issues":  list(self.issues),
        }


# ---------------------------------------------------------------------------
# Manager
# ---------------------------------------------------------------------------

class RootDotfilesManager:
    """Materialise the standard set of dotfiles inside root's home."""

    #: Files that must exist with mode ``0600`` because they contain
    #: sensitive content (history, mail).
    PRIVATE_MODE: int = 0o600

    #: Files that are world-readable (config, shell init).
    SHELL_MODE: int = 0o644

    def __init__(self, home: str) -> None:
        self.home = Path(home)
        self._templates: Dict[str, str] = dict(DEFAULT_TEMPLATES)
        self._mode_overrides: Dict[str, int] = {
            ".bash_history": 0o600,
            ".lesshst":      0o600,
            ".viminfo":      0o600,
        }

    # -- template registration -------------------------------------------

    def register_template(self, name: str, content: str) -> None:
        self._templates[name] = content

    def set_mode_override(self, name: str, mode: int) -> None:
        self._mode_overrides[name] = mode

    # -- ensure ----------------------------------------------------------

    def ensure(self, name: str, *, force: bool = False) -> DotfileResult:
        """Materialise one dotfile.  ``force=True`` overwrites an
        existing file (the default behaviour is "do not touch")."""
        if name not in self._templates:
            raise KeyError(f"no template registered for {name!r}")
        path = self.home / name
        mode = self._mode_overrides.get(name, self.SHELL_MODE)
        body = self._render(self._templates[name])
        created = False
        updated = False
        if not path.exists():
            path.write_text(body, encoding="utf-8")
            created = True
        else:
            existing = path.read_text(encoding="utf-8", errors="replace")
            current_mode = stat.S_IMODE(path.stat().st_mode)
            content_differs = existing != body
            mode_differs = current_mode != mode
            if (content_differs or mode_differs) and not force:
                return DotfileResult(
                    name=name,
                    path=str(path),
                    created=False, updated=False,
                    mode=current_mode,
                    size_bytes=path.stat().st_size,
                    note="exists with different content or mode; pass force=True to overwrite",
                )
            if content_differs:
                path.write_text(body, encoding="utf-8")
                updated = True
            if mode_differs:
                updated = True
        try:
            os.chmod(path, mode)
        except OSError as exc:
            log.warning("could not chmod %s: %s", path, exc)
        st = path.stat()
        return DotfileResult(
            name=name,
            path=str(path),
            created=created, updated=updated,
            mode=stat.S_IMODE(st.st_mode),
            size_bytes=st.st_size,
        )

    def ensure_all(self, *, force: bool = False) -> DotfilesReport:
        report = DotfilesReport(home=str(self.home))
        if not self.home.is_dir():
            report.issues.append(f"{self.home} is not a directory")
            return report
        for name in self._templates:
            try:
                result = self.ensure(name, force=force)
                report.results.append(result)
            except OSError as exc:
                report.issues.append(f"{name}: {exc}")
        return report

    # -- private file helpers -------------------------------------------

    def ensure_private_file(self, name: str, content: str = "") -> DotfileResult:
        """Materialise a private (mode ``0600``) file - typically
        ``.bash_history``, ``.viminfo`` or ``.lesshst``.
        """
        path = self.home / name
        if not path.exists():
            path.write_text(content, encoding="utf-8")
            created = True
        else:
            created = False
        try:
            os.chmod(path, self.PRIVATE_MODE)
        except OSError as exc:
            log.warning("could not chmod %s: %s", path, exc)
        st = path.stat()
        return DotfileResult(
            name=name,
            path=str(path),
            created=created, updated=False,
            mode=stat.S_IMODE(st.st_mode),
            size_bytes=st.st_size,
        )

    # -- inventory -------------------------------------------------------

    def list_present(self) -> List[str]:
        if not self.home.is_dir():
            return []
        return sorted(p.name for p in self.home.iterdir() if p.name.startswith("."))

    def list_missing(self) -> List[str]:
        present = set(self.list_present())
        return sorted(n for n in self._templates if n not in present)

    # -- internals -------------------------------------------------------

    @staticmethod
    def _render(template: str) -> str:
        return template.format(
            generated_at=_dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        )


# ---------------------------------------------------------------------------
# Self-test
# ---------------------------------------------------------------------------

def _selftest() -> bool:
    import tempfile
    with tempfile.TemporaryDirectory() as tmp:
        home = Path(tmp) / "root"
        home.mkdir()
        mgr = RootDotfilesManager(home=str(home))
        # Default templates should include the standard four.
        for required in (".bashrc", ".bash_profile", ".profile", ".bash_logout", ".vimrc"):
            if required not in mgr._templates:
                return False
        report = mgr.ensure_all()
        if not report.results:
            return False
        if any(r.created for r in report.results) is False:
            return False
        # Files must now exist.
        for name in mgr._templates:
            if not (home / name).is_file():
                return False
        # Private file.
        priv = mgr.ensure_private_file(".bash_history")
        if not priv.created:
            return False
        st = (home / ".bash_history").stat()
        if os.name != "nt" and stat.S_IMODE(st.st_mode) != 0o600:
            return False
        # Re-running should be a no-op (no creation, no update).
        report2 = mgr.ensure_all()
        if any(r.created for r in report2.results):
            return False
        if any(r.updated for r in report2.results):
            return False
        # Custom template + force.
        mgr.register_template(".myrc", "hello world\\n")
        r1 = mgr.ensure(".myrc")
        if not r1.created:
            return False
        r2 = mgr.ensure(".myrc")
        if r2.updated:
            return False
        mgr.set_mode_override(".myrc", 0o640)
        r3 = mgr.ensure(".myrc", force=True)
        if not r3.updated:
            return False
    return True


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    print("dotfiles selftest:", "OK" if _selftest() else "FAIL")
